apiVersion: batch/v1
kind: Job
metadata:
  name: rag-ingest-full
  namespace: dosm-dev
spec:
  ttlSecondsAfterFinished: 86400  # Clean up after 24 hours
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ingest
          image: dosmfaqchatbotacr1lw5a.azurecr.io/dosm-faq-chatbot:d72386a
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              echo "[info] Downloading dataset from DOSM..."
              python3 -c "
              import urllib.request
              url = 'https://storage.dosm.gov.my/labour/lfs_month_duration.csv'
              urllib.request.urlretrieve(url, '/tmp/lfs_month_duration.csv')
              print(f'Downloaded to /tmp/lfs_month_duration.csv')
              "
              echo "[info] Dataset downloaded, $(wc -l < /tmp/lfs_month_duration.csv) rows"
              echo "[info] Starting ingestion..."
              python -m train.train_rag_assets --input /tmp/lfs_month_duration.csv
              echo "[done] Ingestion complete"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dev-db-url
                  key: DATABASE_URL
            - name: EMBEDDING_MODEL_NAME
              value: "sentence-transformers/all-MiniLM-L6-v2"
            - name: MODEL_VERSION
              value: "dosm-rag-full-$(date +%Y%m%d)"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
