apiVersion: v1
kind: ConfigMap
metadata:
  name: dosm-sample-data
  namespace: dosm-dev
data:
  dosm_sample.csv: |
    year,indicator,value,notes
    2022,CPI,118.4,Consumer Price Index base 2015=100
    2023,CPI,121.0,Moderate inflation increase
    2023,UnemploymentRate,3.5,Percentage of labor force unemployed
    2024,CPI,123.2,Projected CPI early estimate
    2024,UnemploymentRate,3.4,Slight improvement year over year
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rag-ingest-sample
  namespace: dosm-dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ingest
          image: dosmfaqchatbotacr1lw5a.azurecr.io/dosm-faq-chatbot:88849d5
          command:
            - python
            - -m
            - train.train_rag_assets
          args:
            - --input
            - /data/dosm_sample.csv
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dev-db-url
                  key: DATABASE_URL
            - name: EMBEDDING_MODEL_NAME
              value: "sentence-transformers/all-MiniLM-L6-v2"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          configMap:
            name: dosm-sample-data
